#!/usr/bin/env bash

set -euo pipefail

#-------------------------------------------------------------------------------
#
# Mingw GCC build script
# Author: Sebastien Alaiwan, largely inspired by the one made by venix
# Date: 2013-09-29
#
# The basic steps are:
# 0) Download and extract all the required packages
# 1) build the binutils, ./configure with --target=$(TARGET)
# 2) install the binutils: make install
# 3) build the core-gcc, configure with --target=$(TARGET), make all-gcc
# 4) install the core-gcc: make install-gcc
# 5) build the mingw runtime (libc) using the core-gcc
# 6) finish building gcc: go back to the core-gcc build directory and run "make"
# 7) install gcc: make install
#-------------------------------------------------------------------------------
#readonly TARGET=x86_64-w64-mingw32
readonly TARGET=i686-ace-mingw32
readonly PREFIX=/tmp/gdc-release

readonly SERVER_URL=http://ftp.gnu.org/gnu
readonly GCC_VERSION=5.3.0
readonly BINUTILS_VERSION=2.25

readonly GCC_LANGS="c,c++,d"

readonly BIN=bin
readonly ARCHIVES=archives

readonly scriptDir=$(realpath $(dirname $0))

unset CC
unset CXX
readonly MAKE="make -j8 -k"

function main
{
  mkdir -p $ARCHIVES
  mkdir -p src bin

  lazy binutils_download
  lazy binutils_build

  lazy mingw64_download
  lazy mingw64_extract
  lazy mingw64_install_headers

  lazy gcc_download
  lazy gcc_extract
  lazy gcc_patch

  lazy gdc_download
  lazy gdc_apply

  lazy gcc_configure
  lazy gcc_standalone_build
  lazy gcc_standalone_install

  lazy mingw64_build
  lazy gcc_build

  lazy gcc_install

  export PATH="$PREFIX/bin:$PATH"
  export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig

  lazy sdl_install
  lazy mikmod_install
  #lazy sdlmixer_install
  #lazy zlib_install
  lazy sdlimage_install

  trap - EXIT
  echo Done
}

#-------------------------------------------------------------------------------
# BINUTILS
#-------------------------------------------------------------------------------
readonly BINUTILS_SRC=src/binutils
readonly BINUTILS_BIN=bin/binutils

function binutils_download
{
	wget "$SERVER_URL/binutils/binutils-$BINUTILS_VERSION.tar.bz2" -O "$ARCHIVES/binutils.tar.bz2"
}

function binutils_build
{
  extract_to "$ARCHIVES/binutils.tar.bz2" $BINUTILS_SRC

	rm -rf "$BINUTILS_BIN"
	mkdir -p "$BINUTILS_BIN"
  readonly DIR=$(realpath $BINUTILS_SRC)
	pushd "$BINUTILS_BIN"
  $DIR/configure \
    --prefix="$PREFIX" \
    --target=$TARGET \
    --disable-nls --with-gcc --with-gnu-as --with-gnu-ld \
    --disable-shared 2>&1 >/dev/null
  popd

	$MAKE -C "$BINUTILS_BIN" CFLAGS="-O2 -fno-exceptions" LDFLAGS="-s"
	$MAKE -C "$BINUTILS_BIN" install
}

#-------------------------------------------------------------------------------
# MINGW 64 (LIBC)
#-------------------------------------------------------------------------------
MINGW64_SRC=src/mingw64
MINGW64_BIN=bin/mingw64

function mingw64_download
{
	wget "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v3.0.0.tar.bz2" -O "$ARCHIVES/mingw64.tar.bz2"
}

function mingw64_extract
{
  extract_to $ARCHIVES/mingw64.tar.bz2 $MINGW64_SRC
}

function mingw64_install_headers # "sys-include"
{
  rm -rf "bin/mingw64-headers"
  mkdir -p "bin/mingw64-headers"
  local dir=$(realpath $MINGW64_SRC)

  pushd bin/mingw64-headers
  $dir/mingw-w64-headers/configure --host=$TARGET --prefix="$PREFIX/$TARGET"
  popd

  $MAKE -C bin/mingw64-headers
  $MAKE -C bin/mingw64-headers install
}

function mingw64_build
{
  rm -rf "$MINGW64_BIN"
  mkdir -p "$MINGW64_BIN"

  local dir=$(realpath $MINGW64_SRC)

  pushd "$MINGW64_BIN"
  $dir/configure --host=$TARGET --prefix="$PREFIX/$TARGET" PATH="$PREFIX/bin:$PATH"
  popd

  $MAKE -C "$MINGW64_BIN" PATH="$PREFIX/bin:$PATH"
  $MAKE -C "$MINGW64_BIN" install PATH="$PREFIX/bin:$PATH"
}

##-------------------------------------------------------------------------------
## GCC CORE
##-------------------------------------------------------------------------------
readonly GCC_SRC=src/gcc
readonly GCC_BIN=bin/gcc

function gcc_download
{
  wget "$SERVER_URL/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.bz2" -O $ARCHIVES/gcc.tar.bz2
}

function gcc_extract
{
  extract_to $ARCHIVES/gcc.tar.bz2 $GCC_SRC

  pushd $GCC_SRC
  ./contrib/download_prerequisites
  popd
}

function gcc_patch
{
  patch -p1 --merge -d $GCC_SRC < $scriptDir/patches/gcc/0001-Remove-fPIC-for-MinGW.patch
}

function gcc_configure
{
  local dir=$(realpath $GCC_SRC)
  mkdir -p "$GCC_BIN"
  pushd $GCC_BIN
  $dir/configure \
    -v \
    --disable-bootstrap \
     --without-headers \
     --enable-targets=all \
     --prefix="$PREFIX" \
     --target="$TARGET" \
     --enable-languages=$GCC_LANGS \
     --with-gcc --with-gnu-ld --with-gnu-as \
     --enable-threads \
     --disable-nls \
     --disable-win32-registry \
     --disable-shared \
     --enable-sjlj-exceptions \
     --disable-java-awt \
     --without-x \
     --enable-lto
  popd
}

function gcc_standalone_build
{
  $MAKE all-gcc           -C "$GCC_BIN"
  $MAKE all-target-libgcc -C "$GCC_BIN"
}

function gcc_standalone_install
{
  $MAKE -C "$GCC_BIN" install-gcc
}

function gcc_build
{
  $MAKE all -C "$GCC_BIN"
}

function gcc_install
{
	$MAKE install -C "$GCC_BIN"
}

#------------------------------------------------------------------------------
# GDC
#------------------------------------------------------------------------------
function gdc_download
{
  rm -rf src/gdc
  git clone https://github.com/D-Programming-GDC/GDC.git src/gdc
  pushd src/gdc
  git checkout origin/gdc-5
  popd
}

function gdc_apply
{
	pushd src/gdc
  ./setup-gcc.sh ../gcc
  popd
}

function extract_to
{
  local file=$1
  local dir=$2

	tar xlf "$file"
	rm -rf "$dir"
	mv "`tar tlf $file 2>/dev/null | head -n 1 | cut -f 1 -d '/'`" "$dir"
}

#------------------------------------------------------------------------------
# SDL
#------------------------------------------------------------------------------
function sdl_install
{
  wget http://libsdl.org/release/SDL-1.2.15.tar.gz -O $ARCHIVES/sdl.tar.gz
  extract_to "$ARCHIVES/sdl.tar.gz" src/sdl
  mkdir -p bin/sdl
  pushd bin/sdl
  ../../src/sdl/configure \
    --host=$TARGET \
    --prefix=$PREFIX
  $MAKE
  $MAKE install
  popd
}

function mikmod_install
{
  wget http://downloads.sourceforge.net/project/mikmod/libmikmod/3.3.8/libmikmod-3.3.8.tar.gz -O $ARCHIVES/libmikmod.tar.gz
  extract_to "$ARCHIVES/libmikmod.tar.gz" src/mikmod
  mkdir -p bin/mikmod
  pushd bin/mikmod
  ../../src/mikmod/configure \
    --host=$TARGET \
    --prefix=$PREFIX
  $MAKE
  $MAKE install
  popd
}

function sdlmixer_install
{
  wget https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz -O $ARCHIVES/sdlmixer.tar.gz
  extract_to "$ARCHIVES/sdlmixer.tar.gz" src/sdlmixer
  mkdir -p bin/sdlmixer
  pushd bin/sdlmixer
  ../../src/sdlmixer/configure \
    --disable-sdltest \
    --disable-esdtest \
    --disable-smpegtest \
    --disable-music-cmd \
    --host=$TARGET \
    --prefix=$PREFIX
  $MAKE
  $MAKE install
  popd
}

function sdlimage_install
{
  wget https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz -O $ARCHIVES/sdlimage.tar.gz
  extract_to "$ARCHIVES/sdlimage.tar.gz" src/sdlimage
  mkdir -p bin/sdlimage
  pushd bin/sdlimage
  ../../src/sdlimage/configure \
    --host=$TARGET \
    --prefix=$PREFIX
  $MAKE
  $MAKE install
  popd
}

function lazy
{
  local readonly func="$1"

  if [ -f $BIN/flags/$func ] ; then
    return 0
  fi

  echo "$func ..."
  $func & # fork: prevent the callee to change the caller's environment
  pid=$!
  wait $pid

  mkdir -p $BIN/flags
  touch $BIN/flags/$func
}

main "$@"

