#!/usr/bin/env bash

set -euo pipefail

#-------------------------------------------------------------------------------
#
# Mingw GCC build script
# Author: Sebastien Alaiwan, largely inspired by the one made by venix
# Date: 2013-09-29
#
# The basic steps are:
# 0) Download and extract all the required packages
# 1) build the binutils, ./configure with --target=$(TARGET)
# 2) install the binutils: make install
# 3) build the core-gcc, configure with --target=$(TARGET), make all-gcc
# 4) install the core-gcc: make install-gcc
# 5) build the mingw runtime (libc) using the core-gcc
# 6) finish building gcc: go back to the core-gcc build directory and run "make"
# 7) install gcc: make install
#-------------------------------------------------------------------------------
readonly TARGET=i686-ace-mingw32
readonly PREFIX=/tmp/gdc-release-w32

readonly scriptDir=$(realpath $(dirname $0))
source $scriptDir/base.sh

function main
{
  mkdir -p $ARCHIVES
  mkdir -p src bin

  lazy binutils_download
  lazy binutils_build

  lazy mingw64_download
  lazy mingw64_extract
  lazy mingw64_install_headers

  lazy gcc_download
  lazy gcc_extract
  lazy gcc_patch

  lazy gdc_download
  lazy gdc_apply

  lazy gcc_configure
  lazy gcc_standalone_build
  lazy gcc_standalone_install

  lazy mingw64_build

  lazy gcc_build
  lazy gcc_install

  echo Done
}

#-------------------------------------------------------------------------------
# BINUTILS
#-------------------------------------------------------------------------------
readonly BINUTILS_SRC=src/binutils
readonly BINUTILS_BIN=bin/binutils

function binutils_download
{
	wget "$SERVER_URL/binutils/binutils-$BINUTILS_VERSION.tar.bz2" -O "$ARCHIVES/binutils.tar.bz2"
}

function binutils_build
{
  extract_to "$ARCHIVES/binutils.tar.bz2" $BINUTILS_SRC

	rm -rf "$BINUTILS_BIN"
	mkdir -p "$BINUTILS_BIN"
  readonly DIR=$(realpath $BINUTILS_SRC)
	pushd "$BINUTILS_BIN"
  $DIR/configure \
    --prefix="$PREFIX" \
    --target=$TARGET \
    --disable-nls --with-gcc --with-gnu-as --with-gnu-ld \
    --disable-shared 2>&1 >/dev/null
  popd

	$MAKE -C "$BINUTILS_BIN" CFLAGS="-O2 -fno-exceptions" LDFLAGS="-s"
	$MAKE -C "$BINUTILS_BIN" install
}

#-------------------------------------------------------------------------------
# MINGW 64 (LIBC)
#-------------------------------------------------------------------------------
MINGW64_SRC=src/mingw64
MINGW64_BIN=bin/mingw64

function mingw64_download
{
	wget "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v3.0.0.tar.bz2" -O "$ARCHIVES/mingw64.tar.bz2"
}

function mingw64_extract
{
  extract_to $ARCHIVES/mingw64.tar.bz2 $MINGW64_SRC
}

function mingw64_install_headers # "sys-include"
{
  rm -rf "bin/mingw64-headers"
  mkdir -p "bin/mingw64-headers"
  local dir=$(realpath $MINGW64_SRC)

  pushd bin/mingw64-headers
  $dir/mingw-w64-headers/configure --host=$TARGET --prefix="$PREFIX/$TARGET"
  popd

  $MAKE -C bin/mingw64-headers
  $MAKE -C bin/mingw64-headers install
}

function mingw64_build
{
  rm -rf "$MINGW64_BIN"
  mkdir -p "$MINGW64_BIN"

  local dir=$(realpath $MINGW64_SRC)

  pushd "$MINGW64_BIN"
  $dir/configure --host=$TARGET --prefix="$PREFIX/$TARGET" PATH="$PREFIX/bin:$PATH"
  popd

  $MAKE -C "$MINGW64_BIN" PATH="$PREFIX/bin:$PATH"
  $MAKE -C "$MINGW64_BIN" install PATH="$PREFIX/bin:$PATH"
}

##-------------------------------------------------------------------------------
## GCC CORE
##-------------------------------------------------------------------------------
readonly GCC_SRC=src/gcc
readonly GCC_BIN=bin/gcc

function gcc_download
{
  wget "$SERVER_URL/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.bz2" -O $ARCHIVES/gcc.tar.bz2
}

function gcc_extract
{
  extract_to $ARCHIVES/gcc.tar.bz2 $GCC_SRC

  pushd $GCC_SRC
  ./contrib/download_prerequisites
  popd
}

function gcc_patch
{
  patch -p1 --merge -d $GCC_SRC < $scriptDir/patches/gcc/0001-Remove-fPIC-for-MinGW.patch
}

function gcc_configure
{
  local dir=../../$GCC_SRC # 'dir' must be a relative path, otherwise GMP will not build under Msy2/Cygwin
  mkdir -p "$GCC_BIN"
  pushd $GCC_BIN
  $dir/configure \
    -v \
    --disable-bootstrap \
     --without-headers \
     --enable-targets=all \
     --prefix="$PREFIX" \
     --target="$TARGET" \
     --enable-languages=$GCC_LANGS \
     --with-gcc --with-gnu-ld --with-gnu-as \
     --enable-threads \
     --disable-nls \
     --disable-win32-registry \
     --disable-shared \
     --disable-multilib \
     --enable-sjlj-exceptions \
     --disable-java-awt \
     --without-x \
     --enable-lto
  popd
}

function gcc_standalone_build
{
  $MAKE all-gcc           -C "$GCC_BIN"
  $MAKE all-target-libgcc -C "$GCC_BIN"
}

function gcc_standalone_install
{
  $MAKE -C "$GCC_BIN" install-gcc
}

function gcc_build
{
  $MAKE all -C "$GCC_BIN"
}

function gcc_install
{
	$MAKE install -C "$GCC_BIN"
}

#------------------------------------------------------------------------------
# GDC
#------------------------------------------------------------------------------
function gdc_download
{
  rm -rf src/gdc
  git clone https://github.com/D-Programming-GDC/GDC.git src/gdc
  pushd src/gdc
  git checkout origin/gdc-5
  popd
}

function gdc_apply
{
	pushd src/gdc
  ./setup-gcc.sh ../gcc
  popd
}

#------------------------------------------------------------------------------

main "$@"

